// Test script for OpenAI reverse prompt generation
const documentAnalysisService = require('./server/services/documentAnalysisService');
const fs = require('fs');

async function testOpenAIReversePrompt() {
    try {
        // Read the test file
        const testFile = './test_decision_tree_english.txt';
        const content = fs.readFileSync(testFile, 'utf8').toString();
        
        console.log('=== Test OpenAI Reverse Prompt Generation ===');
        console.log('Test file:', testFile);
        console.log('File length:', content.length, 'characters');
        console.log('\n--- File Content (First 200 chars) ---');
        console.log(content.substring(0, 200) + '...');
        
        // Create file info
        const fileInfo = {
            name: 'test_decision_tree_english.txt',
            size: content.length,
            type: 'text/plain'
        };
        
        // Analyze content first
        console.log('\n--- Analyzing Content ---');
        const analysis = documentAnalysisService.analyzeContent(content, fileInfo);
        
        // Generate reverse prompt using the improved async method
        console.log('\n--- Generating Reverse Prompt with OpenAI ---');
        const reversePromptResult = await documentAnalysisService.generateReversePrompt(analysis, content);
        
        console.log('\n--- Reverse Prompt Results ---');
        console.log('Generated by:', reversePromptResult.generatedBy);
        console.log('Confidence:', reversePromptResult.confidence);
        console.log('\nReverse Prompt:');
        console.log(reversePromptResult.reversePrompt);
        
        console.log('\n--- Structured Details ---');
        console.log(JSON.stringify(reversePromptResult.structuredDetails, null, 2));
        
        console.log('\n=== Test Complete ===');
        
    } catch (error) {
        console.error('Error during testing:', error);
        console.error('Stack trace:', error.stack);
    }
}

// Run the test
testOpenAIReversePrompt();
