/**
 * Idea to Prompt Service
 * 创意转提示词服务 - 基于逆向提示词工程最佳实践
 * 
 * 核心原理：
 * 1. 深度分析输入内容，提取关键要素
 * 2. 识别写作风格、语气、结构
 * 3. 构建结构化提示词模板
 * 4. 质量验证确保提示词有效
 */

const logger = require('../config/logger');
const aiService = require('./ai-service');
const taskManager = require('./task-manager');
const qualityService = require('./prompt-quality-service');

class IdeaToPromptService {
  constructor() {
    this.contentCategory = {
      copywriting: '文案',
      image: '图片',
      video: '视频',
      audio: '音频'
    };
  }

  async generatePrompt(content, category = 'copywriting') {
    if (!content || typeof content !== 'string') {
      throw new Error('内容无效，必须是字符串');
    }

    const sourceLanguage = qualityService.detectSourceLanguage(content);
    const hasChinese = sourceLanguage === 'chinese' || sourceLanguage === 'mixed';
    
    logger.info(`开始生成反推提示词，语言检测: ${sourceLanguage}`);

    const aiAnalysis = await this.analyzeWithAI(content, hasChinese);
    
    if (!aiAnalysis) {
      throw new Error('AI分析失败，请检查API密钥配置或网络连接。');
    }
    
    logger.info('AI分析成功，生成有意义的主题和摘要');
    
    const analysis = this.analyzeContent(content, aiAnalysis);
    
    const structuredDetails = this.generateStructuredDetails(analysis, hasChinese);
    
    let englishPrompt = this.buildEnglishPrompt(structuredDetails, analysis, hasChinese);
    
    let chinesePrompt = this.translateToChinese(englishPrompt);
    
    const processed = qualityService.processPrompts(englishPrompt, chinesePrompt, sourceLanguage);
    
    englishPrompt = processed.englishPrompt;
    chinesePrompt = processed.chinesePrompt;
    
    if (processed.englishIssues.length > 0) {
      logger.warn('English prompt quality issues:', processed.englishIssues);
    }
    if (processed.chineseIssues.length > 0) {
      logger.warn('Chinese prompt quality issues:', processed.chineseIssues);
    }
    
    const qualityReport = qualityService.generateQualityReport(englishPrompt, chinesePrompt);
    
    logger.info('提示词生成完成，质量等级:', qualityReport.overallQuality);
    
    return {
      englishPrompt: englishPrompt,
      chinesePrompt: chinesePrompt,
      reversePrompt: englishPrompt,
      structuredDetails: structuredDetails,
      analysis: analysis,
      confidence: this.calculateConfidence(analysis),
      generatedBy: 'IdeaToPromptService (AI enhanced)',
      qualityReport: qualityReport,
      sourceLanguage: sourceLanguage
    };
  }

  async analyzeWithAI(content, hasChinese) {
    try {
      const prompt = hasChinese 
        ? this._buildChineseAnalysisPrompt(content)
        : this._buildEnglishAnalysisPrompt(content);

      const result = await aiService.callModel(prompt, { maxTokens: 1000 });
      
      if (!result || !result.success) {
        return null;
      }

      try {
        return JSON.parse(result.content);
      } catch {
        return {
          topic: result.content.substring(0, 50),
          summary: result.content,
          keywords: [],
          style: 'informative',
          tone: 'neutral'
        };
      }
    } catch (error) {
      logger.error('AI分析失败:', error.message);
      return null;
    }
  }

  _buildChineseAnalysisPrompt(content) {
    return `请分析以下中文内容并提取关键信息：\n\n${content}\n\n请以JSON格式输出：
{
  "topic": "主题",
  "summary": "内容摘要",
  "keywords": ["关键词1", "关键词2"],
  "style": "写作风格",
  "tone": "语气",
  "keyPoints": ["要点1", "要点2"],
  "targetAudience": "目标受众"
}`;
  }

  _buildEnglishAnalysisPrompt(content) {
    return `Analyze the following content and extract key information:\n\n${content}\n\nPlease output in JSON format:
{
  "topic": "topic",
  "summary": "content summary",
  "keywords": ["keyword1", "keyword2"],
  "style": "writing style",
  "tone": "tone",
  "keyPoints": ["point1", "point2"],
  "targetAudience": "target audience"
}`;
  }

  analyzeContent(content, aiAnalysis) {
    const cleaned = this.cleanContent(content);
    const sentences = this.extractSentences(cleaned);
    const paragraphs = this.extractParagraphs(cleaned);
    
    const topic = aiAnalysis?.topic || 'content analysis';
    const style = aiAnalysis?.style || 'informative';
    const tone = aiAnalysis?.tone || 'neutral';
    
    let keywords = [];
    if (aiAnalysis?.keywords) {
      keywords = Array.isArray(aiAnalysis.keywords) 
        ? aiAnalysis.keywords.slice(0, 10)
        : aiAnalysis.keywords.split(',').map(k => k.trim()).filter(k => k.length > 0).slice(0, 10);
    }
    
    let keyElements = [];
    if (aiAnalysis?.keyPoints) {
      keyElements = Array.isArray(aiAnalysis.keyPoints) 
        ? aiAnalysis.keyPoints.slice(0, 8)
        : aiAnalysis.keyPoints.split(',').map(k => k.trim()).filter(k => k.length > 0).slice(0, 8);
    }
    
    const aiSummary = aiAnalysis?.summary || 'Content summary generated by AI analysis';
    const targetAudience = aiAnalysis?.audience || aiAnalysis?.targetAudience || 'general audience';
    
    return {
      originalContent: content,
      cleanedContent: cleaned,
      sentences: sentences,
      paragraphs: paragraphs,
      length: content.length,
      topic: topic,
      style: style,
      tone: tone,
      keywords: keywords,
      keyElements: keyElements,
      summary: aiSummary,
      targetAudience: targetAudience,
      aiAnalysis: aiAnalysis
    };
  }

  cleanContent(content) {
    return content
      .replace(/[\r\n]+/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  extractSentences(content) {
    const hasChinese = /[\u4e00-\u9fa5]/.test(content);
    const regex = hasChinese ? /[。！？；]+/g : /[.!?]+/g;
    return content.split(regex).map(s => s.trim()).filter(s => s.length > 0);
  }

  extractParagraphs(content) {
    return content.split(/\n\n+/).map(p => p.trim()).filter(p => p.length > 0);
  }

  generateStructuredDetails(analysis, hasChinese) {
    return {
      basicStructure: {
        singleWords: analysis.keywords.length > 0 
          ? analysis.keywords.slice(0, 8).join(hasChinese ? '、' : ', ') 
          : (hasChinese ? '文档' : 'document'),
        phrasePrompts: analysis.keyElements.length > 0 
          ? analysis.keyElements.slice(0, 4).join(hasChinese ? '、' : ', ') 
          : (hasChinese ? '文档内容' : 'document content'),
        completeSentences: analysis.summary
      },
      applicationStructure: {
        copywritingStyle: hasChinese ? this.getChineseCopywritingStyle(analysis.style) : this.getEnglishCopywritingStyle(analysis.style)
      },
      functionalElements: {
        subject: analysis.topic,
        style: analysis.style,
        sceneAction: hasChinese ? '围绕主题展开' : 'develop around the main topic',
        details: hasChinese ? '清晰、简洁、有条理' : 'clear, concise, well-organized',
        positive: hasChinese ? '清晰、简洁、结构良好、信息丰富、引人入胜' : 'clear, concise, well-structured, informative, engaging',
        negative: hasChinese ? '避免重复、无冗余、不过于冗长' : 'avoid repetition, no redundancy, not too verbose'
      },
      targetAudience: analysis.targetAudience,
      confidence: this.calculateConfidence(analysis)
    };
  }

  getChineseCopywritingStyle(style) {
    const styles = {
      'informative': '信息型',
      'persuasive': '说服型',
      'narrative': '叙事型',
      'descriptive': '描述型',
      'technical': '技术型'
    };
    return styles[style] || style;
  }

  getEnglishCopywritingStyle(style) {
    const styles = {
      '信息型': 'informative',
      '说服型': 'persuasive',
      '叙事型': 'narrative',
      '描述型': 'descriptive',
      '技术型': 'technical'
    };
    return styles[style] || style;
  }

  buildEnglishPrompt(structuredDetails, analysis, hasChinese) {
    const parts = [];
    
    const subject = structuredDetails.functionalElements.subject || 'content';
    const summary = structuredDetails.basicStructure.completeSentences || '';
    const style = structuredDetails.applicationStructure.copywritingStyle || 'informative';
    const audience = structuredDetails.targetAudience || 'general audience';
    const keyElements = structuredDetails.basicStructure.phrasePrompts || '';
    
    parts.push(`Generate content about: ${subject}`);
    
    if (summary && summary.trim().length > 0 && !summary.includes('undefined') && !summary.includes('未提供')) {
      parts.push(`Content summary: ${summary}`);
    }
    
    parts.push(`Style: ${style}`);
    parts.push(`Target audience: ${audience}`);
    
    if (keyElements && keyElements.trim().length > 0 && !keyElements.includes('undefined') && !keyElements.includes('未提供')) {
      parts.push(`Key elements: ${keyElements}`);
    }
    
    if (analysis.keywords && analysis.keywords.length > 0) {
      const validKeywords = analysis.keywords.filter(k => k && k.trim().length > 0 && !k.includes('undefined') && !k.includes('未提供'));
      if (validKeywords.length > 0) {
        parts.push(`Keywords: ${validKeywords.join(', ')}`);
      }
    }
    
    let prompt = parts.join('. ');
    
    prompt = this.cleanPrompt(prompt);
    
    if (!prompt.endsWith('.')) {
      prompt += '.';
    }
    
    return prompt;
  }

  cleanPrompt(prompt) {
    if (!prompt) return '';
    
    let cleaned = prompt;
    
    cleaned = cleaned.replace(/undefined/g, '');
    cleaned = cleaned.replace(/未提供/g, '');
    
    cleaned = cleaned.replace(/[，,、]+/g, ', ');
    
    cleaned = cleaned.replace(/\.\s*\./g, '.');
    
    cleaned = cleaned.replace(/:\s*:/g, ':');
    
    cleaned = cleaned.replace(/\s+/g, ' ');
    
    cleaned = cleaned.replace(/,\s*,/g, ',');
    
    cleaned = cleaned.replace(/:\s*,/g, ': ');
    
    cleaned = cleaned.replace(/^[.,\s]+|[.,\s]+$/g, '');
    
    cleaned = cleaned.replace(/\.\s*([A-Z])/g, '. $1');
    
    return cleaned.trim();
  }

  translateToChinese(englishPrompt) {
    const translations = [
      ['Generate content about:', '生成关于'],
      ['Content summary:', '内容摘要：'],
      ['Style:', '风格：'],
      ['Target audience:', '目标受众：'],
      ['Key elements:', '关键要素：'],
      ['Keywords:', '关键词：'],
      ['informative', '信息型'],
      ['persuasive', '说服型'],
      ['narrative', '叙事型'],
      ['descriptive', '描述型'],
      ['technical', '技术型'],
      ['general audience', '普通大众'],
      ['clear', '清晰'],
      ['concise', '简洁'],
      ['well-structured', '结构良好']
    ];

    let result = englishPrompt;
    for (const [en, zh] of translations) {
      result = result.replace(new RegExp(en, 'gi'), zh);
    }
    
    return result;
  }

  calculateConfidence(analysis) {
    let score = 70;
    
    if (analysis.keywords && analysis.keywords.length >= 5) score += 10;
    if (analysis.keyElements && analysis.keyElements.length >= 3) score += 10;
    if (analysis.summary && analysis.summary.length > 50) score += 10;
    
    return Math.min(100, score);
  }

  async generatePromptAsync(content, category = 'copywriting') {
    const taskId = taskManager.createTask('prompt-generation', { content, category });
    
    return new Promise((resolve, reject) => {
      const checkInterval = setInterval(() => {
        const task = taskManager.getTask(taskId);
        if (!task) {
          clearInterval(checkInterval);
          reject(new Error('任务不存在'));
          return;
        }
        
        if (task.status === 'completed') {
          clearInterval(checkInterval);
          resolve({
            taskId,
            ...task.result
          });
        } else if (task.status === 'failed') {
          clearInterval(checkInterval);
          reject(new Error(task.error || '任务失败'));
        }
      }, 100);
    });
  }
}

module.exports = new IdeaToPromptService();